sudo: required
services:
  - docker
language: python
python:
  # to test project against python 3.6
  - "3.6"
  # to test project against pypy also
  ## Commented As Only Want Commit from Python3.6 Machine
  ##- "pypy"
# command to install dependencies
branches:
  only:
    - /^master.*$/
    - /^release.*$/
    - /^hotfix.*$/
    - /^quality.*$/
    - /^develop.*$/
    - /^feature.*$/
    - /^[vrbfhdq]?\d+\.\d+\.\d+$/

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
# command to run tests
script:
  # Echo TravisCI built in enviornment variables
  - echo $TRAVIS_BUILD_NUMBER
  - echo ${TRAVIS_BUILD_NUMBER}
  - echo "$TRAVIS_BUILD_NUMBER"
  - echo "${TRAVIS_BUILD_NUMBER}"
  - echo "BuildID#" ${TRAVIS_BUILD_ID}
  - echo "BuildID# ${TRAVIS_BUILD_ID}"
  - echo 'BuildID# ${TRAVIS_BUILD_ID}'
  - echo $GITHUB_PAT
  - export TEST=Hello
  - echo $TEST
  - echo $(git log --format=%h -1)
  # Execute tests
  - pytest
  # Make docs using Sphinx
  - rm -rf .\docs\_build
  - cd docs
  - make clean
  - make html
  - cd ..
  # Build all distros - src, binary and windows wheel
  - rm -rf dist/
  - rm -rf sg_downloader.egg-info/
  - python setup.py sdist bdist bdist_wheel --universal
