sudo: required
services:
  - docker
language: python
python:
  # to test project against python 3.6
  - "3.6"
  # to test project against pypy also
  ## Commented As Only Want Commit from Python3.6 Machine
  ##- "pypy"
# command to install dependencies
branches:
  only:
    - /^master.*$/
    - /^release.*$/
    - /^hotfix.*$/
    - /^quality.*$/
    - /^develop.*$/
    - /^feature.*$/
    - /^[vrbfhdq]?\d+\.\d+\.\d+$/
    - tags
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
# command to run tests
script:
  # Echo TravisCI built in enviornment variables
  - echo "^^^ TravisCI Diagnostics Variables ^^^"
  - echo "Build No & ID = ${TRAVIS_BUILD_NUMBER} and ${TRAVIS_BUILD_ID}"
  - echo "Job No & ID = ${TRAVIS_JOB_NUMBER} & ${TRAVIS_JOB_ID}"
  - echo "Commit ID = ${TRAVIS_COMMIT}"
  - echo "Commit Message = ${TRAVIS_COMMIT_MESSAGE}"
  - echo "Repo Slug = ${TRAVIS_REPO_SLUG}"
  - echo "Build Directory = ${TRAVIS_BUILD_DIR}"
  - echo "OS Name = ${TRAVIS_OS_NAME}"

  - echo "^^^ Other Diagnostics Variable ^^^"
  - echo "Github PAT = ${GITHUB_PAT}"
  - echo "Git Reference = $(git log --format=%h -1)"

  # Execute tests
  - pytest

  # Make docs using Sphinx
  - rm -rf .\docs\_build
  - cd docs
  - make clean
  - make html
  - cd ..

  # Build all distros - src, binary and windows wheel
  - rm -rf dist/
  - rm -rf sg_downloader.egg-info/
  - python setup.py sdist bdist bdist_wheel --universal

# As per [this](https://docs.travis-ci.com/user/deployment/releases/) either set your build to deploy only when
# the build already has a tag using 'on.tags: true', or manually tag the commit with git tag in before_deploy.
# Hence i'll tag the commit manually here for TravisCI. This needs to be done in "before_deploy" section
before_deploy:
  # 1. Setup GIT User Name & EMail for TravisCI
  - git config --global credential.helper store
  - git config --local user.name "sachin-gupta"
  - git config --local user.email "sachin.aut@gmail.com"

  # 2. Create Tag (Locally) To Push
  # Note: Build will fail if tag exsist thus using repo reference to tag
  #- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - echo git tag \"$(git log --format=%h -1)\"
  - git tag "$(git log --format=%h -1)"

# Deployment of desired branches and tags only
deploy:
  provider: releases
  api_key: \"${GITHUB_PAT}\"
  file_glob: true
  file: dist/**/*
  # Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created during the build, which will probably delete what you are trying to upload.
  skip_cleanup: true
  # Make sure to set overwrite: true as writing to same tag again and again
  overwrite: true
  # Deplyoment conditions for TravisCI (https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A)
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|release|hotfix|develop$
  # Commented as I am tagging manually becasue I don't want only tags to get deployed
  #  tags: true

# Arrest email notifications on build success
notifications:
  email:
    on_success: never
    on_failure: always
