language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # to test project against pypy
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
# command to run tests
script:
  # Execute tests
  - pytest
  # Make docs
  - rm -rf .\docs\_build
  - cd docs
  - make clean
  - make html
  - cd ..
  # Build distributions
  - python setup.py sdist bdist bdist_wheel --universal
